title: Relaso CRM
description: Official Site of the Relaso CRM
url: https://relaso.com
baseurl: ""
relative_url: true

plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag

show_drafts: 'true'

sass:
  style: compressed
  sass_options:
    quiet: true # Suppress warnings


# pagination:
#   enabled: true
#   per_page: 8
#   title: ":title - Page :num"
#   indexpage: 'blog'

defaults:
  # Set permalinks for all posts
  - scope:
      path: "_posts"
      type: "posts"
    values:
      permalink: "/blog/:title/"